apiVersion: v1
kind: Service
metadata:
  name: cbdc
  namespace: default
spec:
  ports:
    - name: protocol
      port: 8333
      targetPort: 8333
  selector:
    service: cbdc
  type: LoadBalancer
  externalTrafficPolicy: Local
